export type Talk = {
  id: number;
  title: string;
  presenter: string;
  email: string;
  duration: number;
  topic: string;
  description: string;
  status: "pending" | "approved" | "rejected";
  date_submitted: string;
  image_url: string;
  presentation_date: string;
  venue: string;
  user_id: number;
  fullname: string;
  has_presentation?: boolean;
  presentation_url?: string;
  allow_archive?: boolean;
  presentation_start_time?: string;
};
